# Lab 8.04

## Instructions

Following the class example, create a function that returns the price, names of origin and arrival airports and the name of the company. Do it for all the flights between two dates that cost the same.

In [1]:
import requests
import pandas as pd
import json

In [7]:
import requests

url = "https://travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com/v1/prices/calendar"

querystring = {"calendar_type":"departure_date","destination":"GYD","origin":"BER","depart_date":"2020-06-24","currency":"EUR"}

headers = {
	"X-Access-Token": "87ebfac8abf48390faad848a0a10fb48",
	"X-RapidAPI-Host": "travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com",
	"X-RapidAPI-Key": "9a91d30288mshe8ef7d16db4b168p1a6634jsnb3ce38ae86d7"
}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

{"success":true,"data":{"2022-04-28":{"origin":"BER","destination":"BAK","price":723,"airline":"XQ","flight_number":947,"departure_at":"2022-04-28T14:40:00+02:00","return_at":"2022-04-29T21:45:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-04-30":{"origin":"BER","destination":"BAK","price":678,"airline":"XQ","flight_number":967,"departure_at":"2022-04-30T06:45:00+02:00","return_at":"2022-05-02T05:15:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-02":{"origin":"BER","destination":"BAK","price":651,"airline":"PC","flight_number":980,"departure_at":"2022-05-02T13:10:00+02:00","return_at":"2022-05-03T07:45:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-04":{"origin":"BER","destination":"BAK","price":299,"airline":"W6","flight_number":2316,"departure_at":"2022-05-04T08:20:00+02:00","return_at":"2022-05-24T09:45:00+04:00","transfers":2,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-06":{"origin":"BER","destination":"BAK","price":553,"airline":"TK","flight_number":1728,"departure_at":"2022-05-06T07:00:00+02:00","return_at":"2022-05-08T21:45:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-08":{"origin":"BER","destination":"BAK","price":449,"airline":"","flight_number":1726,"departure_at":"2022-05-08T14:55:00+02:00","return_at":"2022-05-21T06:55:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-10":{"origin":"BER","destination":"BAK","price":449,"airline":"","flight_number":1726,"departure_at":"2022-05-10T14:55:00+02:00","return_at":"2022-05-20T06:55:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-11":{"origin":"BER","destination":"BAK","price":354,"airline":"AL","flight_number":196,"departure_at":"2022-05-11T11:35:00+02:00","return_at":"2022-05-18T09:45:00+04:00","transfers":2,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-29":{"origin":"BER","destination":"BAK","price":312,"airline":"FR","flight_number":4732,"departure_at":"2022-05-29T06:15:00+02:00","return_at":"2022-06-07T09:45:00+04:00","transfers":3,"expires_at":"2022-04-29T22:12:43Z"},"2022-05-31":{"origin":"BER","destination":"BAK","price":361,"airline":"AL","flight_number":144,"departure_at":"2022-05-31T06:30:00+02:00","return_at":"2022-06-01T09:45:00+04:00","transfers":2,"expires_at":"2022-04-29T22:12:43Z"},"2022-06-12":{"origin":"BER","destination":"BAK","price":331,"airline":"U2","flight_number":8126,"departure_at":"2022-06-12T21:35:00+02:00","return_at":"2022-06-20T09:45:00+04:00","transfers":3,"expires_at":"2022-04-29T22:12:43Z"},"2022-06-14":{"origin":"BER","destination":"BAK","price":321,"airline":"FR","flight_number":1148,"departure_at":"2022-06-14T06:05:00+02:00","return_at":"2022-07-12T09:45:00+04:00","transfers":3,"expires_at":"2022-04-29T22:12:43Z"},"2022-06-21":{"origin":"BER","destination":"BAK","price":441,"airline":"J2","flight_number":64,"departure_at":"2022-06-21T10:55:00+02:00","return_at":"2022-07-12T07:00:00+04:00","transfers":0,"expires_at":"2022-04-29T22:12:43Z"},"2022-06-29":{"origin":"BER","destination":"BAK","price":404,"airline":"LO","flight_number":388,"departure_at":"2022-06-29T11:45:00+02:00","return_at":"2022-07-06T06:00:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-07-03":{"origin":"BER","destination":"BAK","price":459,"airline":"","flight_number":64,"departure_at":"2022-07-03T10:55:00+02:00","return_at":"2022-07-24T07:00:00+04:00","transfers":0,"expires_at":"2022-04-29T22:12:43Z"},"2022-07-10":{"origin":"BER","destination":"BAK","price":459,"airline":"J2","flight_number":64,"departure_at":"2022-07-10T10:55:00+02:00","return_at":"2022-07-17T03:45:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-07-16":{"origin":"BER","destination":"BAK","price":820,"airline":"QR","flight_number":82,"departure_at":"2022-07-16T16:40:00+02:00","return_at":"2022-08-13T03:25:00+04:00","transfers":1,"expires_at":"2022-04-29T22:12:43Z"},"2022-07-17":{"origin":"BER","destination":"BAK","price":463,"airline":"J2","flight_number":64,"departure_at":"2022-07-17T10:55:00+02:00","return_at":"2022-07-31T07:00:00+04:00","transfers":0,"expires_at":"2022-04-29T22:12:43Z"},"2022-08-14":{"origin":"BER","destination":"BAK","price":441,"airline":"J2","flight_number":64,"departure_at":"2022-08-14T10:55:00+02:00","return_at":"2022-08-28T07:00:00+04:00","transfers":0,"expires_at":"2022-04-29T22:12:43Z"}},"currency":"EUR"}

In [8]:
response.json()

{'success': True,
 'data': {'2022-04-28': {'origin': 'BER',
   'destination': 'BAK',
   'price': 723,
   'airline': 'XQ',
   'flight_number': 947,
   'departure_at': '2022-04-28T14:40:00+02:00',
   'return_at': '2022-04-29T21:45:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-04-30': {'origin': 'BER',
   'destination': 'BAK',
   'price': 678,
   'airline': 'XQ',
   'flight_number': 967,
   'departure_at': '2022-04-30T06:45:00+02:00',
   'return_at': '2022-05-02T05:15:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-02': {'origin': 'BER',
   'destination': 'BAK',
   'price': 651,
   'airline': 'PC',
   'flight_number': 980,
   'departure_at': '2022-05-02T13:10:00+02:00',
   'return_at': '2022-05-03T07:45:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-04': {'origin': 'BER',
   'destination': 'BAK',
   'price': 299,
   'airline': 'W6',
   'flight_number': 2316,
   'departure_at': '2022-05-04T08:20:00+02:00',
   'return_at': '2022-05-24T09:45:00+04:00',
   'transfers': 2,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-06': {'origin': 'BER',
   'destination': 'BAK',
   'price': 553,
   'airline': 'TK',
   'flight_number': 1728,
   'departure_at': '2022-05-06T07:00:00+02:00',
   'return_at': '2022-05-08T21:45:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-08': {'origin': 'BER',
   'destination': 'BAK',
   'price': 449,
   'airline': '',
   'flight_number': 1726,
   'departure_at': '2022-05-08T14:55:00+02:00',
   'return_at': '2022-05-21T06:55:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-10': {'origin': 'BER',
   'destination': 'BAK',
   'price': 449,
   'airline': '',
   'flight_number': 1726,
   'departure_at': '2022-05-10T14:55:00+02:00',
   'return_at': '2022-05-20T06:55:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-11': {'origin': 'BER',
   'destination': 'BAK',
   'price': 354,
   'airline': 'AL',
   'flight_number': 196,
   'departure_at': '2022-05-11T11:35:00+02:00',
   'return_at': '2022-05-18T09:45:00+04:00',
   'transfers': 2,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-29': {'origin': 'BER',
   'destination': 'BAK',
   'price': 312,
   'airline': 'FR',
   'flight_number': 4732,
   'departure_at': '2022-05-29T06:15:00+02:00',
   'return_at': '2022-06-07T09:45:00+04:00',
   'transfers': 3,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-05-31': {'origin': 'BER',
   'destination': 'BAK',
   'price': 361,
   'airline': 'AL',
   'flight_number': 144,
   'departure_at': '2022-05-31T06:30:00+02:00',
   'return_at': '2022-06-01T09:45:00+04:00',
   'transfers': 2,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-06-12': {'origin': 'BER',
   'destination': 'BAK',
   'price': 331,
   'airline': 'U2',
   'flight_number': 8126,
   'departure_at': '2022-06-12T21:35:00+02:00',
   'return_at': '2022-06-20T09:45:00+04:00',
   'transfers': 3,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-06-14': {'origin': 'BER',
   'destination': 'BAK',
   'price': 321,
   'airline': 'FR',
   'flight_number': 1148,
   'departure_at': '2022-06-14T06:05:00+02:00',
   'return_at': '2022-07-12T09:45:00+04:00',
   'transfers': 3,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-06-21': {'origin': 'BER',
   'destination': 'BAK',
   'price': 441,
   'airline': 'J2',
   'flight_number': 64,
   'departure_at': '2022-06-21T10:55:00+02:00',
   'return_at': '2022-07-12T07:00:00+04:00',
   'transfers': 0,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-06-29': {'origin': 'BER',
   'destination': 'BAK',
   'price': 404,
   'airline': 'LO',
   'flight_number': 388,
   'departure_at': '2022-06-29T11:45:00+02:00',
   'return_at': '2022-07-06T06:00:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-07-03': {'origin': 'BER',
   'destination': 'BAK',
   'price': 459,
   'airline': '',
   'flight_number': 64,
   'departure_at': '2022-07-03T10:55:00+02:00',
   'return_at': '2022-07-24T07:00:00+04:00',
   'transfers': 0,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-07-10': {'origin': 'BER',
   'destination': 'BAK',
   'price': 459,
   'airline': 'J2',
   'flight_number': 64,
   'departure_at': '2022-07-10T10:55:00+02:00',
   'return_at': '2022-07-17T03:45:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-07-16': {'origin': 'BER',
   'destination': 'BAK',
   'price': 820,
   'airline': 'QR',
   'flight_number': 82,
   'departure_at': '2022-07-16T16:40:00+02:00',
   'return_at': '2022-08-13T03:25:00+04:00',
   'transfers': 1,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-07-17': {'origin': 'BER',
   'destination': 'BAK',
   'price': 463,
   'airline': 'J2',
   'flight_number': 64,
   'departure_at': '2022-07-17T10:55:00+02:00',
   'return_at': '2022-07-31T07:00:00+04:00',
   'transfers': 0,
   'expires_at': '2022-04-29T22:12:43Z'},
  '2022-08-14': {'origin': 'BER',
   'destination': 'BAK',
   'price': 441,
   'airline': 'J2',
   'flight_number': 64,
   'departure_at': '2022-08-14T10:55:00+02:00',
   'return_at': '2022-08-28T07:00:00+04:00',
   'transfers': 0,
   'expires_at': '2022-04-29T22:12:43Z'}},
 'currency': 'EUR'}

In [10]:
dates_of_flights = list(response.json()['data'].keys())

In [11]:
response.json()['data'][dates_of_flights[0]]

{'origin': 'BER',
 'destination': 'BAK',
 'price': 723,
 'airline': 'XQ',
 'flight_number': 947,
 'departure_at': '2022-04-28T14:40:00+02:00',
 'return_at': '2022-04-29T21:45:00+04:00',
 'transfers': 1,
 'expires_at': '2022-04-29T22:12:43Z'}

In [12]:
flights = pd.DataFrame(columns=['origin', 'destination', 'price', 'airline', 'flight_number',
       'departure_at', 'return_at', 'transfers', 'expires_at'])

In [13]:
for i in range(len(dates_of_flights)):
    flights = flights.append(pd.json_normalize(response.json()['data'][dates_of_flights[i]]))

In [14]:
flights

,origin,destination,price,airline,flight_number,departure_at,return_at,transfers,expires_at
0,BER,BAK,723,XQ,947,2022-04-28T14:40:00+02:00,2022-04-29T21:45:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,678,XQ,967,2022-04-30T06:45:00+02:00,2022-05-02T05:15:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,651,PC,980,2022-05-02T13:10:00+02:00,2022-05-03T07:45:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,299,W6,2316,2022-05-04T08:20:00+02:00,2022-05-24T09:45:00+04:00,2,2022-04-29T22:12:43Z
0,BER,BAK,553,TK,1728,2022-05-06T07:00:00+02:00,2022-05-08T21:45:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,449,,1726,2022-05-08T14:55:00+02:00,2022-05-21T06:55:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,449,,1726,2022-05-10T14:55:00+02:00,2022-05-20T06:55:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,354,AL,196,2022-05-11T11:35:00+02:00,2022-05-18T09:45:00+04:00,2,2022-04-29T22:12:43Z
0,BER,BAK,312,FR,4732,2022-05-29T06:15:00+02:00,2022-06-07T09:45:00+04:00,3,2022-04-29T22:12:43Z
0,BER,BAK,361,AL,144,2022-05-31T06:30:00+02:00,2022-06-01T09:45:00+04:00,2,2022-04-29T22:12:43Z
0,BER,BAK,331,U2,8126,2022-06-12T21:35:00+02:00,2022-06-20T09:45:00+04:00,3,2022-04-29T22:12:43Z
0,BER,BAK,321,FR,1148,2022-06-14T06:05:00+02:00,2022-07-12T09:45:00+04:00,3,2022-04-29T22:12:43Z
0,BER,BAK,441,J2,64,2022-06-21T10:55:00+02:00,2022-07-12T07:00:00+04:00,0,2022-04-29T22:12:43Z
0,BER,BAK,404,LO,388,2022-06-29T11:45:00+02:00,2022-07-06T06:00:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,459,,64,2022-07-03T10:55:00+02:00,2022-07-24T07:00:00+04:00,0,2022-04-29T22:12:43Z
0,BER,BAK,459,J2,64,2022-07-10T10:55:00+02:00,2022-07-17T03:45:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,820,QR,82,2022-07-16T16:40:00+02:00,2022-08-13T03:25:00+04:00,1,2022-04-29T22:12:43Z
0,BER,BAK,463,J2,64,2022-07-17T10:55:00+02:00,2022-07-31T07:00:00+04:00,0,2022-04-29T22:12:43Z
0,BER,BAK,441,J2,64,2022-08-14T10:55:00+02:00,2022-08-28T07:00:00+04:00,0,2022-04-29T22:12:43Z